spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://localhost:8888"
logging:
  level:
    com.ordersphere.gatewayserver: debug

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true